apiVersion  : v1
name        : App-Web-HelmChart
description : MyHelmForKubernetes
type        : application
version     : 3.15.2 # Version Helm Chart
appVersion  : "1.0.0" # Version of the my app